on:
  push:
    branches:
      - "main"


jobs:
  Env-setup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3.3.0
        with:
          fetch-depth: 0
      - name: export root folder to PYTHONPATH
        run: |
          
          echo $PYTHONPATH
          export PYTHONPAT=$(pwd)
          echo $PYTHONPATH
          