on:
  push:
    branches:
      - "main"


jobs:
  Env-setup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3.3.0
        with:
          fetch-depth: 0
      - name: export root folder to PYTHONPATH
        run: |
          PROJECTPATH=pwd
          export PYTHONPATH=$PROJECTPATH
          echo $PYTHONPATH
      - name: export tests folder to PYTHONPATH
        run: |
          cd test-folder
          TESTSPATH=pwd
          export PYTHONPATH=$PYTHONPATH:$TESTSPATH
      - name: get current PYTHONPATH
        run: echo $PYTHONPATH
      